// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCUTRizYXhnHQEGTxlgd9fNsjrf_8MYQ',
    appId: '1:33530869954:android:21dbdf088f17ef52b6a35b',
    messagingSenderId: '33530869954',
    projectId: 'mlkit-35f9f',
    storageBucket: 'mlkit-35f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUK_8LQiNgT2v9RtzjhHHcLX4QJb6h6b8',
    appId: '1:33530869954:ios:4492382abb214215b6a35b',
    messagingSenderId: '33530869954',
    projectId: 'mlkit-35f9f',
    storageBucket: 'mlkit-35f9f.appspot.com',
    iosClientId: '33530869954-3mikj4t6br7do2a1i5nvk9eunseaqmtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentAutozoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUK_8LQiNgT2v9RtzjhHHcLX4QJb6h6b8',
    appId: '1:33530869954:ios:4492382abb214215b6a35b',
    messagingSenderId: '33530869954',
    projectId: 'mlkit-35f9f',
    storageBucket: 'mlkit-35f9f.appspot.com',
    iosClientId: '33530869954-3mikj4t6br7do2a1i5nvk9eunseaqmtr.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelligentAutozoom',
  );
}
